name: Java CI

on:
  push:
  pull_request:
    types: [opened, synchronize, reopened, edited]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build with Ant
        run: ant -f build-auto.xml dist
      - uses: actions/upload-artifact@v2
        with:
          name: Linux amd64 (64-bit)
          path: [dist/jpcsp-*-linux-amd64.7z]
      - uses: actions/upload-artifact@v2
        with:
          name: Linux x86 (32-bit)
          path: [dist/jpcsp-*-linux-x86.7z]
      - uses: actions/upload-artifact@v2
        with:
          name: Mac OS
          path: [dist/jpcsp-*-macosx.7z]
      - uses: actions/upload-artifact@v2
        with:
          name: Windows amd64 (64-bit)
          path: [dist/jpcsp-*-windows-amd64.7z]
      - uses: actions/upload-artifact@v2
        with:
          name: Windows x86 (32-bit)
          path: [dist/jpcsp-*-windows-x86.7z]